admin:
  - "roadhog_kun"
  - "Nishito_31"
maxchallenge: 3
word:
  - "BAN"
  - "DM"
  - "F3"
  - "F4"
  - "GG"
  - "GM"
  - "OK"
  - "PC"
  - "PVP"
  - "TNT"
  - "a"
  - "help"
  - "http"
  - "kun"
  - "op"
  - "tab"
  - "tp"
  - "w"
  - "x"
  - "youtube"
  - "z"
  - "、"
  - "。"
  - "あ"
  - "ありがとう"
  - "あわせる"
  - "いいですか"
  - "うさぎ"
  - "うし"
  - "うん"
  - "おつ"
  - "おやすみ"
  - "お題"
  - "かまど"
  - "きて"
  - "きのこ"
  - "くも"
  - "ことば"
  - "こんぶ"
  - "じゃま"
  - "すご"
  - "たんぽぽ"
  - "つるはし"
  - "にわとり"
  - "にんじん"
  - "ねこ"
  - "はしご"
  - "へ"
  - "ほら"
  - "まだ"
  - "まる"
  - "も"
  - "もうすぐ"
  - "ゆき"
  - "りんご"
  - "わかった"
  - "ん"
  - "アカシア"
  - "アスレ"
  - "アン"
  - "イカ"
  - "イルカ"
  - "インド"
  - "インベントリ"
  - "ウィザスケ"
  - "ウィザー"
  - "ウィッチ"
  - "エメラルド"
  - "エンダー"
  - "エンダーチェスト"
  - "エンダーマン"
  - "エンチャント"
  - "エンド"
  - "エンドポータル"
  - "オフ"
  - "オーク"
  - "ガラス"
  - "ガーディアン"
  - "キーワード"
  - "クラフト"
  - "クリーパー"
  - "コウモリ"
  - "コマンド"
  - "サトウキビ"
  - "サバイバル"
  - "サンゴ"
  - "ジャングル"
  - "スキップ"
  - "スケルトン"
  - "スニーク"
  - "スポナー"
  - "ソウルサンド"
  - "ゾンビ"
  - "ダイヤ"
  - "ダイヤクワ"
  - "ダメージ"
  - "ダークオーク"
  - "チェスト"
  - "チャット"
  - "チャレンジ"
  - "チャンク"
  - "チート"
  - "ツイッター"
  - "テクスチャ"
  - "テラコッタ"
  - "ディスコード"
  - "トライデント"
  - "トラップ"
  - "トロッコ"
  - "トロール"
  - "ドロップ"
  - "ネザー"
  - "ハチ"
  - "ハニー"
  - "バグ"
  - "バケツ"
  - "バツ"
  - "バージョン"
  - "パウダー"
  - "パン"
  - "ピッグマン"
  - "ピッケル"
  - "ピラミッド"
  - "ファントム"
  - "ブラマイ"
  - "ブロック"
  - "プラグイン"
  - "プレイヤー"
  - "ベッド"
  - "ベリー"
  - "ホラー"
  - "ボタン"
  - "ポーション"
  - "マイクラ"
  - "マウス"
  - "マツ"
  - "マルチ"
  - "メサ"
  - "ラージチェスト"
  - "リスポーン"
  - "ルール"
  - "レッドストーン鉱石"
  - "レンガ"
  - "ログイン"
  - "ワード"
  - "ワープ"
  - "ワールド"
  - "ー"
  - "井戸"
  - "交換"
  - "仕事"
  - "仮拠点"
  - "会議"
  - "作業台"
  - "倉庫"
  - "偶数"
  - "全員"
  - "共有"
  - "出た"
  - "切断"
  - "初期"
  - "判定"
  - "前日"
  - "動画"
  - "協力"
  - "収穫"
  - "呼吸"
  - "回路"
  - "地"
  - "地下"
  - "地図"
  - "夕日"
  - "夜"
  - "夜中"
  - "夜明け"
  - "大きさ"
  - "大陸"
  - "奇数"
  - "学校"
  - "安山岩"
  - "実況"
  - "実績"
  - "家"
  - "寺院"
  - "少ない"
  - "屋敷"
  - "島"
  - "常"
  - "座標"
  - "建築"
  - "強い"
  - "悪"
  - "感"
  - "感圧板"
  - "拠点"
  - "採掘"
  - "操作"
  - "攻撃"
  - "放送"
  - "整地"
  - "日本"
  - "早く"
  - "昨日"
  - "昼"
  - "昼間"
  - "時間"
  - "木"
  - "木材"
  - "本拠点"
  - "村"
  - "東京"
  - "植林"
  - "楽"
  - "死"
  - "毒"
  - "水"
  - "水流"
  - "氷"
  - "沈没船"
  - "泳ぐ"
  - "洞窟"
  - "海底神殿"
  - "深い"
  - "深夜"
  - "渓谷"
  - "溶岩"
  - "無知"
  - "無限水源"
  - "爆発"
  - "爆破"
  - "物資"
  - "画面"
  - "畑"
  - "白"
  - "白樺"
  - "直下掘り"
  - "看板"
  - "着火"
  - "石"
  - "石炭"
  - "砂"
  - "砂利"
  - "砂漠"
  - "破壊"
  - "秒"
  - "竹"
  - "管理"
  - "糸"
  - "経験値"
  - "耐久"
  - "船"
  - "英語"
  - "草"
  - "落下"
  - "行く"
  - "街"
  - "装備"
  - "裏"
  - "襲撃"
  - "要塞"
  - "設定"
  - "誘導"
  - "調子"
  - "謝罪"
  - "豆腐"
  - "資材"
  - "資源"
  - "退出"
  - "遺跡"
  - "配信"
  - "金"
  - "金りんご"
  - "釣り"
  - "鉄つるはし"
  - "鉄鉱石"
  - "関係"
  - "陰"
  - "階段"
  - "雨"
  - "音量"
  - "風"
  - "食料"
  - "馬"
  - "骨粉"
  - "鯖"
  - "黒曜石"
  - "黙"
  - "！"
  - "／word-challenge"
  - "０"
  - "１"
  - "２"
  - "３"
  - "４"
  - "５"
  - "６"
  - "７"
  - "８"
  - "９"
  - "？"