word:
  - "F4"
  - "kun"
  - "あ"
  - "ありがとう"
  - "いいですか"
  - "こんぶ"
  - "ん"
  - "インド"
  - "エンダー"
  - "ダイヤ"
  - "チャット"
  - "ネザー"
  - "バケツ"
  - "ピッケル"
  - "ベッド"
  - "マイクラ"
  - "作業台"
  - "建築"
  - "拠点"
  - "整地"
  - "植林"
  - "爆破"
  - "物資"
  - "畑"
  - "設定"
  - "配信"
  - "金"
  - "釣り"
  - "食料"
  - "鯖"