main: "kun.garrulity.garrulity_jinro.Main"
name: "Garrulity_Jinro"
version: "2.0.3"
api-version: "1.15"
description: "「人狼ジャッジメント」に登場する饒舌な人狼をモチーフとしたプラグインです。\
翌日の朝までにランダムで選ばれるキーワード（お題）を含むワードをチャット欄に入力しない場合、BANとなります。\
また、他のプレイヤーに自身のキーワード（お題）が知られてしまってもBANとなります。"
author: "kasumi-29 (kasumigaura)"
website: "https://github.com/kasumi-29/garrulity_minecraft"

commands:
  key:
    description: "デバッグ用"
    permission: garrulity.op
    usage: "/<command> [SubCommand]"
  word-restart:
    description: "朝にした上で、キーワードを割り振り直します"
    permission: garrulity.op
    usage: "/<command>"
  word-setadmin:
    description: "お題が出題されない、観戦者ロールに追加します"
    permission: garrulity.op
    usage: "/<command> [player]"
  word-deladmin:
    description: "お題が出題されない、観戦者ロールから削除します"
    permission: garrulity.op
    usage: "/<command> [player]"
  word-challenge:
    description: "お題が分かった場合、チャレンジをします"
    permission: garrulity.public
    usage: "
    /<command> [player] [keyword]\n
    使用例:プレイヤー「famas1219」の昨日または今日のお題が「建築」だと推測した場合、次のようにコマンドを入力します。\n\n
    /<command> famas1219 建築\
    "

permissions:
  garrulity.op:
    description: "追加される殆どのコマンドを用いる場合に利用します"
    default: op
  garrulity.public:
    description: "チャレンジコマンドを用いる場合に利用します"
    default: true
  garrulity.debug:
    description: "デバッグ用のコマンドであり、通常は使用しません"
    default: false

